### ISSUE TITLE
lua框架的面向对象问题

### ISSUE THREAD

**Issue by davyxu** [jarjin/LuaFramework_NGUI#4]
LuaFramework\Lua\Controller\PromptCtrl.lua
LuaFramework\Lua\Controller\MessageCtrl.lua

这些文件里用的根本不是面向对象的方式来做, 如果一个界面有多个实例, 或者是有变量需要保存到self上马上就出错了
更别说全局的transform和gameObject
这种设计用意是什么?

**Comment by jarjin** [comment]
简单演示功能，需要self，可自己实现
